import { SummaryListOfEquipmentView } from "../../../../../common/types/equipment-accounting";

export const summaryListOfEquipmentRequestData: SummaryListOfEquipmentView[] = [
  {
    id: "1",
    project: "Новопортовское НГКМ",
    projectId: "1",
    unit: "ОУУ АСВ",
    unitId: "2",
    subUnit: "Линия учета газа от ЦОГ",
    subUnitId: "1",
    installationLocation: "До крана Г-3",
    questionare: "пока нет",
    equipmentType: "СИ",
    systemType: ["РСУ"],
    tag: "PG-3",
    controlledParameter: "Давление газа на входе линии",
    country: "РФ",
    vendor: "Манотомь",
    facilityTitle: "МП-3-У",
    facilityModification: "н/д",
    factoryNumber: "123456",
    year: "2021",
    month: "03",
    period: "120",
    specification: "н/д",
    description: "",
    cableLog: [],
    impulseLineLog: [],
    metrology: {
      id: "1",
      sloeId: "1",
      unit: "ОУУ АСВ",
      unitId: "2",
      subUnit: "Линия учета газа от ЦОГ",
      subUnitId: "1",
      tag: "PG-3",
      sgroei: "СГРОЕИ",
      measurementArea: "Область измерений",
      meansurementType: "Вид измерений",
      meansureGroup: "группа СИ",
      grsi: "unit-1",
      min: "0",
      max: "10",
      range: "МПа",
      accuracy: "+/-1",
      mpi: "60",
      documentType: "Паспорт",
      documentNumber: "№ документа",
      document: "Ссылка на документ",
      counterparty: "Организация, выполнившая поверку",
      fromDate: "2022-05-05 13:34:37.655+03",
      toDate: "2022-05-05 13:34:37.655+03",
      status: "Статус",
      arshin: "Ссылка на АРШИН",
      verificationProcedure: "Ссылка на МП",
      typeApprovalCertificate: "Ссылка на СоУТ",
    },
    signals: [],
  },
  {
    id: "2",
    project: "Новопортовское НГКМ",
    projectId: "1",
    unit: "ОУУ АСВ",
    unitId: "2",
    subUnit: "Линия учета газа от ЦОГ",
    subUnitId: "1",
    installationLocation: "После крана Г-3",
    questionare: "пока нет",
    equipmentType: "СИ",
    systemType: ["РСУ"],
    tag: "PT-3",
    controlledParameter: "Давление газа на входе линии",
    country: "РФ",
    vendor: "Метран",
    facilityTitle: "Метран-150",
    facilityModification: "TG",
    factoryNumber: "678678",
    year: "2022",
    month: "04",
    period: "120",
    specification: "н/д",
    description: "",
    cableLog: [
      {
        id: "1",
        sloeId: "2",
        unit: "ОУУ АСВ",
        unitId: "2",
        subUnit: "Линия учета газа от ЦОГ",
        subUnitId: "1",
        tag: "PT-3",
        wiringDiagramTitle: "wiring-diagram-title",
        numberOfTrace: "number-of-trace",
        cableMark: "cable-mark",
        cableSection: "cable-section",
        fromUnit: "from-unit",
        fromPlace: "fromPlace",
        toUnit: "toUnit",
        toPlace: "toPlace",
        cableLenght: "250",
        range: "м",
        description: "description",
      },
    ],
    impulseLineLog: [
      {
        id: "1",
        sloeId: "2",
        unit: "ОУУ АСВ",
        unitId: "2",
        subUnit: "Линия учета газа от ЦОГ",
        subUnitId: "1",
        tag: "PT-3",
        numberOfTrace: "number-1",
        impulseLineType: "type-1",
        fromPlace: "from-1",
        toPlace: "to-1",
        impulseLineLenght: "34",
        range: "м",
        description: "description-1",
      },
    ],
    metrology: {
      id: "2",
      sloeId: "2",
      unit: "ОУУ АСВ",
      unitId: "2",
      subUnit: "Линия учета газа от ЦОГ",
      subUnitId: "1",
      tag: "PT-3",
      sgroei: "СГРОЕИ",
      measurementArea: "Область измерений",
      meansurementType: "Вид измерений",
      meansureGroup: "группа СИ",
      grsi: "456456",
      min: "0",
      max: "10",
      range: "МПа",
      accuracy: "+/-1",
      mpi: "4",
      documentType: "Паспорт",
      documentNumber: "№ документа",
      document: "Ссылка на документ",
      counterparty: "Организация, выполнившая поверку",
      fromDate: "2022-05-05 13:34:37.655+03",
      toDate: "2029-05-05 13:34:37.655+03",
      status: "Статус",
      arshin: "Ссылка на АРШИН",
      verificationProcedure: "Ссылка на МП",
      typeApprovalCertificate: "Ссылка на СоУТ",
    },
    signals: [
      {
        id: "1",
        sloeId: "2",
        unit: "ОУУ АСВ",
        unitId: "2",
        subUnit: "Линия учета газа от ЦОГ",
        subUnitId: "1",
        tag: "PT-3",
        signalType: "type-1",
        signalProtocol: "protocol-1",
        signalTag: "signal-tag-1",
        ll: "from-1",
        l: "to-1",
        h: "34",
        hh: "м",
        emergenceProtocol: "description-1",
      },
    ],
    monitoring: {
      id: "1",
      sloeId: "2",
      unit: "ОУУ АСВ",
      unitId: "2",
      subUnit: "Линия учета газа от ЦОГ",
      subUnitId: "1",
      tag: "PT-3",
      mountDate: "2022-05-05 13:34:37.655+03",
      mountDocument: "mountDocument",
      connectDate: "2022-05-05 13:34:37.655+03",
      connectDocument: "connectDocument",
      testDate: "2022-05-05 13:34:37.655+03",
      testDocument: "testDocument",
      awpDate: "2022-05-05 13:34:37.655+03",
      awpDocument: "awpDocument",
      commisionDate: "2022-05-05 13:34:37.655+03",
      commisionDocument: "commisionDocument",
      description: "Примечание",
    },
  },
];
