import {
  CableLogView,
  GeneralInformationView,
  ImpulseLineLogView,
  MetrologyView,
  MonitoringView,
  SignalView,
} from "../../../../../common/types/equipment-accounting";

export const cableLog: CableLogView[] = [
  {
    unit: "unit title",
    subUnit: "sub-unit title",
    tag: "equipment-tag",
    wiringDiagramTitle: "wiring-diagram-title",
    numberOfTrace: "number-of-trace",
    cableMark: "cable-mark",
    cableSection: "cable-section",
    fromUnit: "from-unit",
    fromPlace: "fromPlace",
    toUnit: "toUnit",
    toPlace: "toPlace",
    cableLenght: "250",
    range: "м",
    description: "description",
  },
  {
    unit: "unit title-2",
    subUnit: "sub-unit title-2",
    tag: "equipment-tag-2",
    wiringDiagramTitle: "wiring-diagram-title-2",
    numberOfTrace: "number-of-trace-2",
    cableMark: "cable-mark-2",
    cableSection: "cable-section-2",
    fromUnit: "from-unit-2",
    fromPlace: "fromPlace-2",
    toUnit: "toUnit-2",
    toPlace: "toPlace-2",
    cableLenght: "30",
    range: "м",
    description: "description-2",
  },
  {
    unit: "unit title-3",
    subUnit: "sub-unit title-3",
    tag: "equipment-tag-3",
    wiringDiagramTitle: "wiring-diagram-title-3",
    numberOfTrace: "number-of-trace-3",
    cableMark: "cable-mark-3",
    cableSection: "cable-section-3",
    fromUnit: "from-unit-3",
    fromPlace: "fromPlace-3",
    toUnit: "toUnit-3",
    toPlace: "toPlace-3",
    cableLenght: "703",
    range: "м",
    description: "description-3",
  },
];

export const impulseLineLog: ImpulseLineLogView[] = [
  {
    unit: "unit-1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
    subUnit: "sub-unit-1fffffffffffffffffffffffffffffffffffffffffffff",
    tag: "tag-1",
    numberOfTrace: "number-1fffffffffffffffffffffffffffffffffffffffffff",
    impulseLineType: "type-1fffffffffffffffffffffffffffffffffffffffff",
    fromPlace: "from-1ffffffffffffffffffffffffffffffff",
    toPlace: "to-1",
    impulseLineLenght: "34",
    range: "м",
    description: "description-1",
  },
  {
    unit: "unit-1",
    subUnit: "sub-unit-1",
    tag: "tag-1",
    numberOfTrace: "number-1",
    impulseLineType: "type-1",
    fromPlace: "from-1",
    toPlace: "to-1",
    impulseLineLenght: "34",
    range: "м",
    description: "description-1",
  },
  {
    unit: "unit-2",
    subUnit: "sub-unit-2",
    tag: "tag-2",
    numberOfTrace: "number-2",
    impulseLineType: "type-2",
    fromPlace: "from-2",
    toPlace: "to-2",
    impulseLineLenght: "34",
    range: "м",
    description: "description-2",
  },
  {
    unit: "unit-3",
    subUnit: "sub-unit-3",
    tag: "tag-3",
    numberOfTrace: "number-3",
    impulseLineType: "type-3",
    fromPlace: "from-3",
    toPlace: "to-3",
    impulseLineLenght: "34",
    range: "м",
    description: "description-3",
  },
  {
    unit: "unit-4",
    subUnit: "sub-unit-4",
    tag: "tag-4",
    numberOfTrace: "number-4",
    impulseLineType: "type-4",
    fromPlace: "from-4",
    toPlace: "to-4",
    impulseLineLenght: "34",
    range: "м",
    description: "description-4",
  },
];

export const signal: SignalView[] = [
  {
    unit: "unit-1",
    subUnit: "sub-unit-1",
    tag: "tag-1",
    signalType: "type-1",
    signalProtocol: "protocol-1",
    signalTag: "signal-tag-1",
    ll: "from-1",
    l: "to-1",
    h: "34",
    hh: "м",
    emergenceProtocol: "description-1",
  },
];

export const metrology: MetrologyView[] = [
  {
    unit: "unit-1",
    subUnit: "sub-unit-1",
    tag: "tag-1",
    sgroei: "СГРОЕИ",
    measurementArea: "Область измерений",
    meansurementType: "Вид измерений",
    meansureGroup: "группа СИ",
    grsi: "unit-1",
    min: "0",
    max: "10",
    range: "МПа",
    accuracy: "+/-1",
    mpi: "60",
    documentType: "Паспорт",
    documentNumber: "№ документа",
    document: "Ссылка на документ",
    counterparty: "Организация, выполнившая поверку",
    fromDate: "2022-05-05 13:34:37.655+03",
    toDate: "2022-05-05 13:34:37.655+03",
    status: "Статус",
    arshin: "Ссылка на АРШИН",
    verificationProcedure: "Ссылка на МП",
    typeApprovalCertificate: "Ссылка на СоУТ",
  },
];

export const monitoring: MonitoringView[] = [
  {
    unit: "unit-1",
    subUnit: "sub-unit-1",
    tag: "tag-1",
    mountDate: "2022-05-05 13:34:37.655+03",
    mountDocument: "mountDocument",
    connectDate: "2022-05-05 13:34:37.655+03",
    connectDocument: "connectDocument",
    testDate: "2022-05-05 13:34:37.655+03",
    testDocument: "testDocument",
    awpDate: "2022-05-05 13:34:37.655+03",
    awpDocument: "awpDocument",
    commisionDate: "2022-05-05 13:34:37.655+03",
    commisionDocument: "commisionDocument",
    description: "Примечание",
  },
];

export const generalInformation: GeneralInformationView[] = [
  {
    unit: "unit-1",
    subUnit:
      "sub-unit-1gggggggggggggggggggggggggggfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
    installationLocation: "installationLocation",
    questionare: "опросный лист",
    equipmentType: "type",
    systemType: ["systemType", "systemType-2"],
    tag: "tag-1",
    controlledParameter: "controlledParameter",
    country: "country",
    vendor: "vendor",
    facilityTitle: "facilityTitle",
    facilityModification: "facilityModification",
    factoryNumber: "factoryNumber",
    year: "year",
    month: "month",
    period: "period",
    specification: "specification",
    description: "description",
  },
  {
    unit: "unit-1",
    subUnit:
      "sub-unit-1gggggggggggggggggggggggggggfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
    installationLocation: "installationLocation",
    questionare: "опросный лист",
    equipmentType: "type",
    systemType: ["systemType", "systemType-2"],
    tag: "tag-1",
    controlledParameter: "controlledParameter",
    country: "country",
    vendor: "vendor",
    facilityTitle: "facilityTitle",
    facilityModification: "facilityModification",
    factoryNumber: "factoryNumber",
    year: "year",
    month: "month",
    period: "period",
    specification: "specification",
    description: "description",
  },
];
