export const tableLocale = {
  filterTitle: "Filter menu",
  filterConfirm: "OK",
  filterReset: "Сбросить",
  filterEmptyText: "Нет данных",
  filterCheckall: "Выбрать все",
  filterSearchPlaceholder: "Поиск",
  emptyText: "Нет данных",
  selectAll: "Выбрать все",
  selectInvert: "Инвертировать",
  selectNone: "Очистить",
  selectionAll: "Выбрать все",
  sortTitle: "Сортировка",
  expand: "Открыть",
  collapse: "Скрыть",
  triggerDesc: "По убыванию",
  triggerAsc: "По возрастанию",
  cancelSort: "Сбросить",
};
