import {
  FacilityView,
  FacilityCreateOrUpdateAttrs,
  GeneralInformationView,
  GeneralInformationCreateOrUpdateAttrs,
  MetrologyView,
  MetrologyCreateOrUpdateAttrs,
  SignalView,
  SignalCreateOrUpdateAttrs,
  CableLogView,
  CableLogCreateOrUpdateAttrs,
  ImpulseLineLogView,
  ImpulseLineLogCreateOrUpdateAttrs,
  MonitoringView,
  MonitoringCreateOrUpdateAttrs,
  SummaryListOfEquipmentView,
  SummaryListOfEquipmentCreateOrUpdateAttrs,
} from "../../../../../server/common/types/equipment-accounting";

import { Views } from "./equipment-accounting.types";

export type {
  Views,
  FacilityView,
  FacilityCreateOrUpdateAttrs,
  GeneralInformationView,
  GeneralInformationCreateOrUpdateAttrs,
  MetrologyView,
  MetrologyCreateOrUpdateAttrs,
  SignalView,
  SignalCreateOrUpdateAttrs,
  CableLogView,
  CableLogCreateOrUpdateAttrs,
  ImpulseLineLogView,
  ImpulseLineLogCreateOrUpdateAttrs,
  MonitoringView,
  MonitoringCreateOrUpdateAttrs,
  SummaryListOfEquipmentView,
  SummaryListOfEquipmentCreateOrUpdateAttrs,
};
